---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/811a7406-50fc-4fe2-ae38-b1a35086fef9
sections:
- type: heading
  label: Content
- type: directory
  path: src/products
  label: Products
  create: documents
  match: "**/*"
  templates:
  - product
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
- type: heading
  label: Globals
- type: document
  path: src/_data/navigation.json
  label: Navigation
- type: document
  path: src/_data/tokens.json
  label: Theme settings
upload_dir: src/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - ELEVENTY_ENV=staging
  preview_output_directory: src/dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/src"
  instant_preview_command: npm start
