---
label: Product
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: Name
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: categories
  type: tag_list
  default: []
  label: Categories
